/* 词汇真经 · 离线学习引擎。首批词条是依据 PDF 章节结构整理的个人学习种子，可通过 JSON 继续扩充。 */
const CHAPTERS=["自然地理","植物研究","动物保护","太空探索","学校教育","科技发明","文化历史","语言演化","娱乐运动","物品材料","时尚潮流","饮食健康","建筑场所","交通旅行","国家政府","社会经济","法律法规","沙场争锋","社会角色","行为动作","身心健康","时间日期"];
const GROUPS=[
"atmosphere|大气层；气氛|hydrosphere|水圈|lithosphere|岩石圈|altitude|海拔；高度|horizon|地平线；眼界",
"photosynthesis|光合作用|botanical|植物学的|cultivate|种植；培养|seedling|幼苗|biodiversity|生物多样性",
"endanger|危及；使濒危|habitat|栖息地|predator|捕食者|conservation|保护；保存|migrate|迁徙",
"orbit|轨道；绕轨运行|astronaut|宇航员|cosmic|宇宙的|galaxy|星系|exploration|探索",
"curriculum|课程|tuition|学费|literacy|读写能力|assessment|评估|scholarship|奖学金",
"innovation|创新|prototype|原型|automate|使自动化|device|设备|breakthrough|突破",
"heritage|遗产|civilisation|文明|artifact|人工制品；文物|dynasty|王朝|ritual|仪式",
"dialect|方言|linguistic|语言学的|evolve|演变|vocabulary|词汇|bilingual|双语的",
"spectator|观众|tournament|锦标赛|leisure|休闲|athlete|运动员|entertainment|娱乐",
"durable|耐用的|synthetic|合成的|texture|质地|fabric|织物|transparent|透明的",
"trend|趋势|garment|服装|outfit|全套服装|fashionable|时髦的|accessory|配饰",
"nutrition|营养|obesity|肥胖|ingredient|成分；原料|dietary|饮食的|immune|免疫的",
"architecture|建筑学|skyscraper|摩天大楼|venue|场所|renovate|翻新|infrastructure|基础设施",
"itinerary|行程|destination|目的地|commute|通勤|vehicle|车辆|scenic|风景优美的",
"sovereignty|主权|democracy|民主|legislation|立法|citizen|公民|diplomatic|外交的",
"inflation|通货膨胀|revenue|收入；税收|entrepreneur|企业家|inequality|不平等|consumption|消费",
"jurisdiction|司法管辖权|prosecute|起诉|legitimate|合法的|testimony|证词|penalty|惩罚",
"conflict|冲突|alliance|联盟|strategy|策略|defence|防御|casualty|伤亡者",
"colleague|同事|supervisor|主管|volunteer|志愿者|professional|专业人士|empathy|同理心",
"implement|实施|facilitate|促进|trigger|触发|modify|修改|eliminate|消除",
"psychological|心理的|anxiety|焦虑|resilient|有韧性的|wellbeing|福祉|therapy|治疗",
"duration|持续时间|annual|每年的|contemporary|当代的|prior|先前的|simultaneous|同时的"
];
const VERIFIED_IPA={atmosphere:"/ˈætməsfɪə/",hydrosphere:"/ˈhaɪdrəsfɪə/",lithosphere:"/ˈlɪθəsfɪə/",altitude:"/ˈæltɪtjuːd/",horizon:"/həˈraɪzən/",photosynthesis:"/ˌfəʊtəʊˈsɪnθəsɪs/",cultivate:"/ˈkʌltɪveɪt/",biodiversity:"/ˌbaɪəʊdaɪˈvɜːsəti/",endanger:"/ɪnˈdeɪndʒə/",habitat:"/ˈhæbɪtæt/",predator:"/ˈpredətə/",conservation:"/ˌkɒnsəˈveɪʃən/",migrate:"/maɪˈɡreɪt/",orbit:"/ˈɔːbɪt/",astronaut:"/ˈæstrənɔːt/",cosmic:"/ˈkɒzmɪk/",galaxy:"/ˈɡæləksi/",curriculum:"/kəˈrɪkjələm/",tuition:"/tjuˈɪʃən/",literacy:"/ˈlɪtərəsi/",assessment:"/əˈsesmənt/",innovation:"/ˌɪnəˈveɪʃən/",prototype:"/ˈprəʊtətaɪp/",automate:"/ˈɔːtəmeɪt/",device:"/dɪˈvaɪs/",heritage:"/ˈherɪtɪdʒ/",civilisation:"/ˌsɪvəlaɪˈzeɪʃən/",dialect:"/ˈdaɪəlekt/",evolve:"/ɪˈvɒlv/",bilingual:"/baɪˈlɪŋɡwəl/",spectator:"/spekˈteɪtə/",tournament:"/ˈtʊənəmənt/",durable:"/ˈdjʊərəbl/",synthetic:"/sɪnˈθetɪk/",trend:"/trend/",garment:"/ˈɡɑːmənt/",nutrition:"/njuˈtrɪʃən/",obesity:"/əʊˈbiːsəti/",ingredient:"/ɪnˈɡriːdiənt/",architecture:"/ˈɑːkɪtektʃə/",itinerary:"/aɪˈtɪnərəri/",destination:"/ˌdestɪˈneɪʃən/",sovereignty:"/ˈsɒvrənti/",democracy:"/dɪˈmɒkrəsi/",inflation:"/ɪnˈfleɪʃən/",revenue:"/ˈrevənjuː/",entrepreneur:"/ˌɒntrəprəˈnɜː/",inequality:"/ˌɪnɪˈkwɒləti/",jurisdiction:"/ˌdʒʊərɪsˈdɪkʃən/",prosecute:"/ˈprɒsɪkjuːt/",legitimate:"/lɪˈdʒɪtɪmət/",conflict:"/ˈkɒnflɪkt/",strategy:"/ˈstrætədʒi/",defence:"/dɪˈfens/",colleague:"/ˈkɒliːɡ/",supervisor:"/ˈsuːpəvaɪzə/",volunteer:"/ˌvɒlənˈtɪə/",empathy:"/ˈempəθi/",implement:"/ˈɪmplɪment/",facilitate:"/fəˈsɪlɪteɪt/",trigger:"/ˈtrɪɡə/",modify:"/ˈmɒdɪfaɪ/",anxiety:"/æŋˈzaɪəti/",resilient:"/rɪˈzɪliənt/",therapy:"/ˈθerəpi/",duration:"/djʊˈreɪʃən/",annual:"/ˈænjuəl/",contemporary:"/kənˈtempərəri/",prior:"/ˈpraɪə/",simultaneous:"/ˌsɪməlˈteɪniəs/"};
const parseSeed=()=>{const words=[];GROUPS.forEach((g,ci)=>{const p=g.split("|");for(let i=0;i<p.length;i+=2){const word=p[i],meaning=p[i+1];words.push({id:`seed-${ci+1}-${i/2+1}`,word,ipa:VERIFIED_IPA[word]||"待核验",pos:ci%3===0?"n.":ci%3===1?"v.":"adj.",meaning,example:`The study explored ${word} in a changing world.`,exampleZh:`这项研究探讨了变化世界中的${meaning.split("；")[0]}。`,collocations:`understand ${word}; practical ${word}`,etymology:"首批精选词 · 个人学习种子",chapter:CHAPTERS[ci],source_page:String(2+ci*14).padStart(3,"0"),source:"seed",status:"verified",tags:[CHAPTERS[ci]],notes:"",original:{meaning,example:`The study explored ${word} in a changing world.`,exampleZh:`这项研究探讨了变化世界中的${meaning.split("；")[0]}。`,collocations:`understand ${word}`,etymology:"首批精选词"}})}});return words};
const SEED_WORDS=parseSeed();
const KEY="vocab-offline-state-v1";
const defaultState={words:SEED_WORDS,records:{},favorites:[],attempts:[],lastSession:null,settings:{dailyNew:20},theme:"light"};
let state=loadState();
let setup={type:"mixed",count:10,order:"smart",chapter:"all",source:"all"};
let session=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);return {...defaultState,...saved,words:saved.words?.length?saved.words:SEED_WORDS}}}catch(e){}return typeof structuredClone==='function'?structuredClone(defaultState):JSON.parse(JSON.stringify(defaultState))}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2400)}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));if(name==='home')renderHome();if(name==='library')renderLibrary();if(name==='stats')renderStats();window.scrollTo({top:0,behavior:'smooth'})}
function recordFor(id){return state.records[id]||(state.records[id]={level:0,due:null,correct:0,wrong:0,seen:0,lastSeen:null})}
function isDue(w){const r=recordFor(w.id);return !r.due||new Date(r.due)<=new Date()}
function mastered(w){return recordFor(w.id).level>=3}
function todayKey(d=new Date()){return d.toISOString().slice(0,10)}
function streak(){const days=new Set(state.attempts.map(a=>a.date));let d=new Date(),n=0;while(days.has(todayKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function fillSelects(){const opts=CHAPTERS.map(c=>`<option value="${c}">${c}</option>`).join('');$('#chapterSelect').innerHTML='<option value="all">全部主题</option>'+opts;$('#libraryChapter').innerHTML='<option value="all">全部主题</option>'+opts}
function renderHome(){const due=state.words.filter(isDue).length, masteredCount=state.words.filter(mastered).length;$('#todayDue').textContent=due;$('#dueBadge').textContent=`${due} 待复习`;$('#todayMastered').textContent=masteredCount;$('#wrongCount').textContent=`${state.words.filter(w=>recordFor(w.id).wrong>recordFor(w.id).correct).length} 道待巩固`;$('#favoriteCount').textContent=`${state.favorites.length} 个收藏`;const s=streak();$('#streakValue').textContent=`${s} 天`;$('#streakHint').textContent=s?'保持节奏，今天继续':'今天开始第一轮';const today=state.attempts.filter(a=>a.date===todayKey()).length;$('#todayProgressBar').style.width=`${Math.min(100,today/Math.max(1,state.settings.dailyNew)*100)}%`;$('#todayProgressText').textContent=today?`今天已完成 ${today} 道作答`:'今天还没有开始';$('#chapterGrid').innerHTML=CHAPTERS.map(c=>{const ws=state.words.filter(w=>w.chapter===c),done=ws.filter(mastered).length,pct=ws.length?Math.round(done/ws.length*100):0;return `<button class="chapter-card" data-chapter="${c}"><small>${String(CHAPTERS.indexOf(c)+1).padStart(2,'0')} / THEME</small><strong>${c}</strong><div class="mini-track"><span style="width:${pct}%"></span></div><small>${done} / ${ws.length} 已掌握</small></button>`}).join('');$$('.chapter-card').forEach(b=>b.onclick=()=>{setup.chapter=b.dataset.chapter;showView('setup');$('#chapterSelect').value=setup.chapter})}
function renderLibrary(){const q=($('#searchInput')?.value||'').trim().toLowerCase(),ch=$('#libraryChapter')?.value||'all',st=$('#libraryStatus')?.value||'all';let ws=state.words.filter(w=>(ch==='all'||w.chapter===ch)&&(!q||`${w.word} ${w.meaning} ${w.tags?.join(' ')}`.toLowerCase().includes(q))&&statusMatch(w,st));$('#wordTable').innerHTML=ws.length?ws.map(w=>`<div class="word-row"><div class="word-main"><strong>${w.word}</strong><small>${w.ipa} · ${w.pos} · ${w.chapter} · p.${w.source_page}</small></div><div class="word-detail">${w.meaning}<small>${w.notes||w.example}</small></div><div class="word-actions"><button class="mini-btn fav-toggle" data-id="${w.id}">${state.favorites.includes(w.id)?'★':'☆'}</button><button class="mini-btn edit-word" data-id="${w.id}">编辑</button></div></div>`).join(''):'<div class="panel"><p class="muted">没有符合条件的词条。可以清空筛选，或导入自己的 JSON 词库。</p></div>';$$('.fav-toggle').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.id));$$('.edit-word').forEach(b=>b.onclick=()=>openEdit(b.dataset.id))}
function statusMatch(w,st){if(st==='all')return true;if(st==='due')return isDue(w);if(st==='learning')return !mastered(w)&&recordFor(w.id).seen>0;if(st==='mastered')return mastered(w);if(st==='favorite')return state.favorites.includes(w.id);return true}
function renderStats(){const attempts=state.attempts.length,correct=state.attempts.filter(a=>a.correct).length;$('#metricAttempts').textContent=attempts;$('#metricAccuracy').textContent=attempts?`${Math.round(correct/attempts*100)}%`:'0%';$('#metricMastered').textContent=state.words.filter(mastered).length;$('#metricStreak').textContent=streak();const days=[];for(let i=29;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=todayKey(d),n=state.attempts.filter(a=>a.date===k).length;days.push({k,n})}const max=Math.max(1,...days.map(x=>x.n));$('#activityChart').innerHTML=days.map(x=>`<div class="bar" style="height:${Math.max(5,x.n/max*100)}%"><span>${x.k.slice(5)} · ${x.n} 题</span></div>`).join('');$('#chapterStats').innerHTML=CHAPTERS.map(c=>{const ws=state.words.filter(w=>w.chapter===c),pct=ws.length?Math.round(ws.filter(mastered).length/ws.length*100):0;return `<div class="stat-line"><span>${c}</span><strong>${pct}%</strong><div class="mini-track"><span style="width:${pct}%"></span></div></div>`}).join('')}
function toggleFavorite(id){const i=state.favorites.indexOf(id);if(i<0){state.favorites.push(id);toast('已加入收藏')}else{state.favorites.splice(i,1);toast('已取消收藏')}save();renderHome();if($('#view-library').classList.contains('active'))renderLibrary();if(session)renderQuestion()}
function openSetup(kind='mixed'){setup={...setup,type:kind};showView('setup');$$('#typeChoices .choice').forEach(b=>b.classList.toggle('active',b.dataset.type===kind))}
function filteredWords(){return state.words.filter(w=>(setup.chapter==='all'||w.chapter===setup.chapter)&&(setup.source==='all'||w.source===setup.source))}
function makeQueue(){let ws=filteredWords();if(setup.type==='wrong')ws=ws.filter(w=>recordFor(w.id).wrong>recordFor(w.id).correct);if(setup.type==='favorite')ws=ws.filter(w=>state.favorites.includes(w.id));if(setup.type==='mixed')ws=ws.filter(w=>isDue(w)||!recordFor(w.id).seen);if(setup.order==='smart')ws.sort((a,b)=>recordFor(a.id).level-recordFor(b.id).level);if(setup.order==='random')ws.sort(()=>Math.random()-.5);const n=setup.count==='all'?ws.length:Number(setup.count);return ws.slice(0,n).map(w=>({wordId:w.id,status:'pending',attempts:0,selected:null,checked:false,options:null}))}
function startPractice(){const queue=makeQueue();if(!queue.length){toast('当前筛选下没有可练习的词条');return}session={queue,index:0,type:setup.type==='mixed'?['single','fill','spell','listen'][Math.floor(Math.random()*4)]:setup.type,answered:0,correct:0,started:Date.now()};state.lastSession=session;save();showView('practice');renderQuestion()}
function currentItem(){return session?.queue[session.index]}
function currentWord(){return state.words.find(w=>w.id===currentItem()?.wordId)}
function renderQuestion(){const item=currentItem(),w=currentWord();if(!item||!w){finishPractice();return}$('#practiceProgress').textContent=`第 ${session.index+1} / ${session.queue.length} 题`;$('#practiceAccuracy').textContent=`本轮正确率 ${session.answered?Math.round(session.correct/session.answered*100):'--'}%`;$('#railCount').textContent=`${session.index+1}/${session.queue.length}`;$('#questionNav').innerHTML=session.queue.map((q,i)=>`<button class="nav-dot ${i===session.index?'current ':''}${q.status==='correct'?'correct ':''}${q.status==='wrong'?'wrong':''}" data-i="${i}">${i+1}</button>`).join('');$$('.nav-dot').forEach(b=>b.onclick=()=>{session.index=Number(b.dataset.i);renderQuestion()});$('#questionPrompt').textContent=w.word;$('#questionContext').innerHTML=`<span class="badge badge-blue">${w.chapter}</span> <span class="badge">p.${w.source_page}</span> <span class="badge">${w.ipa} · ${w.pos}</span>`;$('#favoriteQuestionBtn').innerHTML=`${state.favorites.includes(w.id)?'★':'☆'} <span>${state.favorites.includes(w.id)?'已收藏':'收藏'}</span>`;$('#favoriteQuestionBtn').onclick=()=>toggleFavorite(w.id);$('#speakBtn').onclick=()=>speak(w.word);$('#explanation').classList.add('hidden');$('#nextQuestionBtn').textContent=item.checked?'下一题 →':'检查答案 →';$('#prevQuestionBtn').disabled=session.index===0;$('#prevQuestionBtn').onclick=()=>{if(session.index>0){session.index--;renderQuestion()}};renderAnswerArea(w,item);}
function answerType(){return session.type==='mixed'?['single','fill','spell','listen'][session.index%4]:session.type}
function renderAnswerArea(w,item){const type=answerType();$('#questionLabel').textContent=type==='fill'?'FILL IN / 语境填空':type==='spell'?'SPELL / 拼写听写':type==='listen'?'LISTEN / 听音辨词':'MEANING / 选择释义';if(type==='single'||type==='multi'||type==='listen'){if(!item.options||item.options.length===0)item.options=makeOptions(w,type==='listen');const options=item.options;$('#answerArea').innerHTML=`<div class="option-list">${options.map((o,i)=>`<button class="answer-option ${item.selected===o?'selected':''} ${item.checked?(o===w.meaning?'correct':'incorrect'):''}" data-value="${o.replace(/"/g,'&quot;')}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`;$$('.answer-option').forEach(b=>b.onclick=()=>{if(item.checked)return;item.selected=b.dataset.value;renderAnswerArea(w,item)})}else{$('#answerArea').innerHTML=`<input class="${type==='spell'?'spell-input':'fill-input'}" id="freeAnswer" placeholder="${type==='spell'?'输入你听到的单词':'输入中文释义关键词'}" value="${item.selected||''}" ${item.checked?'disabled':''} />`;$('#freeAnswer').oninput=e=>item.selected=e.target.value}}
function makeOptions(w,listen){const others=state.words.filter(x=>x.id!==w.id).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.meaning);return [w.meaning,...others].sort(()=>Math.random()-.5)}
function checkAnswer(){const item=currentItem(),w=currentWord();if(!item)return;if(item.checked){if(session.index<session.queue.length-1){session.index++;renderQuestion()}else finishPractice();return}const type=answerType(),value=(item.selected||'').trim();if(!value){toast('先选择或输入答案');return}let ok=false;if(type==='single'||type==='multi'||type==='listen')ok=value===w.meaning;else if(type==='spell')ok=value.toLowerCase()===w.word.toLowerCase();else ok=w.meaning.includes(value)||value.includes(w.meaning.split('；')[0]);item.checked=true;item.status=ok?'correct':'wrong';item.attempts++;session.answered++;if(ok)session.correct++;const r=recordFor(w.id);r.seen++;r.lastSeen=new Date().toISOString();if(ok){r.correct++;r.level=Math.min(4,r.level+1);r.due=new Date(Date.now()+[0,1,3,7,21][r.level]*86400000).toISOString()}else{r.wrong++;r.level=Math.max(0,r.level-1);r.due=new Date().toISOString();if(!session.queue.some((q,i)=>i>session.index&&q.wordId===w.id))session.queue.push({wordId:w.id,status:'pending',attempts:0,selected:null,checked:false})}state.attempts.push({date:todayKey(),id:w.id,correct:ok,mode:type});state.lastSession=session;save();renderQuestion();$('#explanation').innerHTML=`<strong>${ok?'✓ 答对了，继续保持':'再看一眼这个词'}</strong><div><b>${w.word}</b> · ${w.meaning}</div><div>${w.example}<br>${w.exampleZh}</div><small>来源：第 ${w.source_page} 页 · ${w.chapter} · ${w.collocations}</small>`;$('#explanation').classList.remove('hidden');$('#nextQuestionBtn').textContent=session.index<session.queue.length-1?'下一题 →':'查看本轮总结 →';}
function finishPractice(){if(session){state.lastSession=null;save();toast(`本轮完成：${session.correct}/${session.answered} 正确`)}showView('home')}
function speak(word){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}else toast('当前浏览器不支持语音合成')}
function openEdit(id){const w=state.words.find(x=>x.id===id);if(!w)return;$('#editModal').dataset.id=id;$('#editTitle').textContent=w.word;$('#editMeaning').value=w.meaning;$('#editExample').value=`${w.example}\n${w.exampleZh}`;$('#editNotes').value=w.notes||'';$('#editTags').value=(w.tags||[]).join(', ');$('#editModal').classList.remove('hidden')}
function closeEdit(){$('#editModal').classList.add('hidden')}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),words:state.words,records:state.records,favorites:state.favorites,attempts:state.attempts},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vocab-offline-export.json';a.click();URL.revokeObjectURL(a.href);toast('学习数据已导出')}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(Array.isArray(data.words)){state.words=[...state.words.filter(w=>w.source==='seed'),...data.words.map(w=>({...w,source:'imported',status:w.status||'pending',tags:w.tags||[]}))];state.records={...state.records,...(data.records||{})};state.favorites=[...new Set([...state.favorites,...(data.favorites||[])])];save();fillSelects();renderHome();toast(`已导入 ${data.words.length} 个词条`)}else throw Error()}catch(e){toast('导入失败：请检查 JSON 格式')}};reader.readAsText(file)}
function wire(){fillSelects();renderHome();document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v)showView(v);const p=e.target.closest('[data-practice]')?.dataset.practice;if(p){setup.type=p;openSetup(p)}});$('#startTodayBtn').onclick=()=>{setup={...setup,type:'mixed',count:state.settings.dailyNew,chapter:'all',source:'all',order:'smart'};openSetup('mixed');$('#countChoices .choice').forEach(b=>b.classList.toggle('active',b.dataset.count===String(setup.count))) };$('#continueBtn').onclick=()=>{if(state.lastSession){session=state.lastSession;showView('practice');renderQuestion()}else toast('还没有可继续的练习')};$('#launchPracticeBtn').onclick=startPractice;$$('#typeChoices .choice').forEach(b=>b.onclick=()=>{setup.type=b.dataset.type;$$('#typeChoices .choice').forEach(x=>x.classList.toggle('active',x===b))});$$('#countChoices .choice').forEach(b=>b.onclick=()=>{setup.count=b.dataset.count;$$('#countChoices .choice').forEach(x=>x.classList.toggle('active',x===b));$('#previewNumber').textContent=b.dataset.count==='all'?'全部':b.dataset.count});$$('#orderChoices .choice').forEach(b=>b.onclick=()=>{setup.order=b.dataset.order;$$('#orderChoices .choice').forEach(x=>x.classList.toggle('active',x===b))});$('#chapterSelect').onchange=e=>setup.chapter=e.target.value;$('#sourceSelect').onchange=e=>setup.source=e.target.value;$('#nextQuestionBtn').onclick=checkAnswer;$('#exitPractice').onclick=finishPractice;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');state.theme=document.body.classList.contains('dark')?'dark':'light';save()};if(state.theme==='dark')document.body.classList.add('dark');$('#searchInput').oninput=renderLibrary;$('#libraryChapter').onchange=renderLibrary;$('#libraryStatus').onchange=renderLibrary;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#exportBtn').onclick=exportData;$('#closeModal').onclick=closeEdit;$('#cancelEdit').onclick=closeEdit;$('#editForm').onsubmit=e=>{e.preventDefault();const w=state.words.find(x=>x.id===$('#editModal').dataset.id);w.meaning=$('#editMeaning').value;const [en,zh]=($('#editExample').value||'').split('\n');w.example=en||w.example;w.exampleZh=zh||w.exampleZh;w.notes=$('#editNotes').value;w.tags=$('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean);save();closeEdit();renderLibrary();toast('词条已保存')};if('serviceWorker'in navigator&&location.protocol!=='file:'&&!new URLSearchParams(location.search).has('desktop'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
document.addEventListener('DOMContentLoaded',wire);
document.addEventListener('keydown',e=>{if(!session||!document.querySelector('#view-practice')?.classList.contains('active')||e.ctrlKey||e.altKey||e.metaKey)return;if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const n=Number(e.key);if(n>=1&&n<=4){const option=[...document.querySelectorAll('#answerArea .answer-option')][n-1];if(option&&!currentItem()?.checked){e.preventDefault();option.click()}}});
function answerType(){return session?.type==='mixed'?['single','reverse','fill','spell','listen'][session.index%5]:(session?.type||'single')}
function makeOptions(w,reverse=false){const key=reverse?'word':'meaning';const others=state.words.filter(x=>x.id!==w.id).sort(()=>Math.random()-.5).slice(0,3).map(x=>x[key]);return [w[key],...others].sort(()=>Math.random()-.5)}
function renderAnswerArea(w,item){const type=answerType(),reverse=type==='reverse',choice=['single','multi','listen','reverse'].includes(type);$('#questionLabel').textContent=reverse?'MEANING / 看中文选英文':type==='fill'?'FILL IN / 语境填空':type==='spell'?'SPELL / 拼写听写':type==='listen'?'LISTEN / 听音辨词':'MEANING / 选择释义';if(choice){if(!item.options||item.options.length===0)item.options=makeOptions(w,reverse);const target=reverse?w.word:w.meaning;$('#answerArea').innerHTML=`<div class="option-list">${item.options.map((o,i)=>`<button class="answer-option ${item.selected===o?'selected':''} ${item.checked?(o===target?'correct':'incorrect'):''}" data-value="${o.replace(/"/g,'&quot;')}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`;$$('.answer-option').forEach(b=>b.onclick=()=>{if(item.checked)return;item.selected=b.dataset.value;renderAnswerArea(w,item)})}else{$('#answerArea').innerHTML=`<input class="${type==='spell'?'spell-input':'fill-input'}" id="freeAnswer" placeholder="${type==='spell'?'输入你听到的单词':'输入中文释义关键词'}" value="${item.selected||''}" ${item.checked?'disabled':''} />`;$('#freeAnswer').oninput=e=>item.selected=e.target.value}}
function checkAnswer(){const item=currentItem(),w=currentWord();if(!item)return;if(item.checked){if(session.index<session.queue.length-1){session.index++;renderQuestion()}else finishPractice();return}const type=answerType(),value=(item.selected||'').trim();if(!value){toast('先选择或输入答案');return}const reverse=type==='reverse';let ok=false;if(type==='single'||type==='multi'||type==='listen'||reverse)ok=value===(reverse?w.word:w.meaning);else if(type==='spell')ok=value.toLowerCase()===w.word.toLowerCase();else ok=w.meaning.includes(value)||value.includes(w.meaning.split('；')[0]);item.checked=true;item.status=ok?'correct':'wrong';item.attempts++;session.answered++;if(ok)session.correct++;const r=recordFor(w.id);r.seen++;r.lastSeen=new Date().toISOString();if(ok){r.correct++;r.level=Math.min(4,r.level+1);r.due=new Date(Date.now()+[0,1,3,7,21][r.level]*86400000).toISOString()}else{r.wrong++;r.level=Math.max(0,r.level-1);r.due=new Date().toISOString();if(!session.queue.some((q,i)=>i>session.index&&q.wordId===w.id))session.queue.push({wordId:w.id,status:'pending',attempts:0,selected:null,checked:false,options:null})}state.attempts.push({date:todayKey(),id:w.id,correct:ok,mode:type});state.lastSession=session;save();renderQuestion();$('#explanation').innerHTML=`<strong>${ok?'✓ 答对了，继续保持':'再看一眼这个词'}</strong><div><b>${w.word}</b> · ${w.meaning}</div><div>${w.example}<br>${w.exampleZh}</div><small>来源：第 ${w.source_page} 页 · ${w.chapter} · ${w.collocations}</small>`;$('#explanation').classList.remove('hidden');$('#nextQuestionBtn').textContent=session.index<session.queue.length-1?'下一题 →':'查看本轮总结 →'}
document.addEventListener('DOMContentLoaded',()=>{const box=document.querySelector('#typeChoices');if(!box||box.querySelector('[data-type="reverse"]'))return;const b=document.createElement('button');b.className='choice';b.dataset.type='reverse';b.textContent='中选英';b.onclick=()=>{setup.type='reverse';[...box.querySelectorAll('.choice')].forEach(x=>x.classList.toggle('active',x===b))};box.insertBefore(b,box.children[2]||null)});
const _renderAnswerArea=renderAnswerArea;renderAnswerArea=function(w,item){_renderAnswerArea(w,item);if(answerType()==='reverse')$('#questionPrompt').textContent=w.meaning};
const FAMILY_SEEDS=[
 {id:'family-erupt',word:'erupt',ipa:'/ɪˈrʌpt/',pos:'v.',meaning:'爆发；喷发；（斑疹等）突然出现',example:'Lava erupted from the volcano.',exampleZh:'熔岩从火山中喷发出来。',chapter:'自然地理',source_page:'002',family:'eruption',familyOf:null},
 {id:'family-eruption',word:'eruption',ipa:'/ɪˈrʌpʃən/',pos:'n.',meaning:'喷发；爆发',example:'The eruption sent ash high into the sky.',exampleZh:'火山喷发把灰烬送上了高空。',chapter:'自然地理',source_page:'002',family:null,familyOf:'erupt'},
 {id:'family-endangerment',word:'endangerment',ipa:'/ɪnˈdeɪndʒəmənt/',pos:'n.',meaning:'危害；濒危状态',example:'The species faces serious endangerment.',exampleZh:'这个物种正面临严重的濒危状态。',chapter:'动物保护',source_page:'031',family:null,familyOf:'endanger'},
 {id:'family-migration',word:'migration',ipa:'/maɪˈɡreɪʃən/',pos:'n.',meaning:'迁徙；移居',example:'Bird migration follows seasonal patterns.',exampleZh:'鸟类迁徙遵循季节规律。',chapter:'动物保护',source_page:'031',family:null,familyOf:'migrate'},
 {id:'family-innovation',word:'innovative',ipa:'/ˈɪnəvətɪv/',pos:'adj.',meaning:'创新的',example:'The team developed an innovative device.',exampleZh:'团队开发了一种创新设备。',chapter:'科技发明',source_page:'085',family:null,familyOf:'innovation'},
 {id:'family-consumption',word:'consume',ipa:'/kənˈsjuːm/',pos:'v.',meaning:'消费；消耗',example:'Buildings consume a large amount of energy.',exampleZh:'建筑物消耗大量能源。',chapter:'社会经济',source_page:'197',family:null,familyOf:'consumption'},
 {id:'family-legislation',word:'legislate',ipa:'/ˈledʒɪsleɪt/',pos:'v.',meaning:'立法；制定法律',example:'Governments legislate to protect public health.',exampleZh:'政府通过立法保护公共健康。',chapter:'法律法规',source_page:'213',family:null,familyOf:'legislation'},
 {id:'family-psychology',word:'psychology',ipa:'/saɪˈkɒlədʒi/',pos:'n.',meaning:'心理学；心理状态',example:'The course introduces basic psychology.',exampleZh:'这门课程介绍基础心理学。',chapter:'身心健康',source_page:'275',family:null,familyOf:'psychological'}
].map(x=>({...x,source:'family',status:'verified',tags:[x.chapter,'词族'],notes:'来自 PDF 词条下方的同根词/词族扩展',collocations:'',etymology:'词族扩展',original:{meaning:x.meaning,example:x.example,exampleZh:x.exampleZh}}));
function ensureFamilyWords(){const existing=new Set(state.words.map(w=>w.id));const additions=FAMILY_SEEDS.filter(w=>!existing.has(w.id));if(additions.length){state.words.push(...additions);save();toast(`已加入 ${additions.length} 个词族词条`)}}
document.addEventListener('DOMContentLoaded',()=>{ensureFamilyWords();fillSelects();renderHome()});
function repairSavedIpa(){let changed=false;state.words.forEach(w=>{if(w.source!=='seed')return;const next=VERIFIED_IPA[w.word]||'待核验';if(w.ipa!==next){w.ipa=next;changed=true}});if(changed)save()}
document.addEventListener('DOMContentLoaded',()=>{repairSavedIpa();renderHome()});
document.addEventListener('DOMContentLoaded',()=>{if(!Array.isArray(window.FULL_OCR_WORDS))return;const byWord=new Map(state.words.map(w=>[w.word.toLowerCase(),w]));let added=0;window.FULL_OCR_WORDS.forEach(o=>{const key=o.word.toLowerCase();const existing=byWord.get(key);if(existing){existing.occurrences=Math.max(existing.occurrences||1,o.occurrences||1);existing.source_pages=[...new Set([...(existing.source_pages||[]),...(o.source_pages||[])])];return}state.words.push(o);byWord.set(key,o);added++});if(added){save();fillSelects();renderHome();toast(`全书 OCR 词库已加载：新增 ${added} 词条`)}});
document.addEventListener('DOMContentLoaded',()=>{const s=$('#sourceSelect');if(s&&!s.querySelector('[value="ocr"]')){const o=document.createElement('option');o.value='ocr';o.textContent='全书 OCR（待核验）';s.appendChild(o)}});
function wholeBookWords(){const seen=new Set();return state.words.filter(w=>{const k=w.word.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const ar=recordFor(a.id),br=recordFor(b.id);return (ar.level-br.level)||(ar.seen-br.seen)||Number(a.source_page||999)-Number(b.source_page||999)})}
function makeWholeQueue(){return wholeBookWords().slice(0,50).flatMap(w=>[{wordId:w.id,variant:0,status:'pending',attempts:0,selected:null,checked:false,options:null},{wordId:w.id,variant:1,status:'pending',attempts:0,selected:null,checked:false,options:null}])}
function renderWholeProgress(){const total=wholeBookWords().length,seen=wholeBookWords().filter(w=>recordFor(w.id).seen>0).length,mastered=wholeBookWords().filter(w=>recordFor(w.id).level>=3).length,left=Math.max(0,total-seen),pct=total?Math.round(seen/total*100):0;let panel=$('#wholeProgressPanel');if(!panel&&$('#chapterGrid')){$('#chapterGrid').insertAdjacentHTML('beforebegin','<article id="wholeProgressPanel" class="panel whole-progress"><div class="panel-head"><div><p class="eyebrow">FULL BOOK / 整本遍历</p><h2>全书背诵进度</h2></div><span class="badge badge-blue" id="wholeProgressPct">0%</span></div><div class="whole-progress-numbers"><div><strong id="wholeSeen">0</strong><span>已背过</span></div><div><strong id="wholeMastered">0</strong><span>已掌握</span></div><div><strong id="wholeLeft">0</strong><span>尚未开始</span></div></div><div class="progress-track"><span id="wholeProgressBar"></span></div><p class="muted">整本遍历每天抽取 50 个词，每个词出现两次，共 100 题。</p></article>');panel=$('#wholeProgressPanel')}if(panel){$('#wholeSeen').textContent=seen;$('#wholeMastered').textContent=mastered;$('#wholeLeft').textContent=left;$('#wholeProgressPct').textContent=`${pct}%`;$('#wholeProgressBar').style.width=`${pct}%`}}
const _homeWithProgress=renderHome;renderHome=function(){_homeWithProgress();renderWholeProgress()};
const _startPracticeWithWhole=startPractice;startPractice=function(){if(setup.type!=='whole')return _startPracticeWithWhole();const queue=makeWholeQueue();if(!queue.length){toast('全书词库暂无可练习词条');return}session={queue,index:0,type:'whole',answered:0,correct:0,started:Date.now()};state.lastSession=session;save();showView('practice');renderQuestion()};
function answerType(){const item=currentItem();if(session?.type==='whole')return item?.variant===1?'reverse':'single';return session?.type==='mixed'?['single','reverse','fill','spell','listen'][session.index%5]:(session?.type||'single')}
document.addEventListener('DOMContentLoaded',()=>{const box=$('#typeChoices');if(box&&!box.querySelector('[data-type="whole"]')){const b=document.createElement('button');b.className='choice';b.dataset.type='whole';b.textContent='整本遍历';b.onclick=()=>{setup.type='whole';setup.count=100;$('#previewNumber').textContent='100';[...box.querySelectorAll('.choice')].forEach(x=>x.classList.toggle('active',x===b))};box.appendChild(b)}const quick=$('.quick-grid');if(quick&&!quick.querySelector('[data-practice="whole"]')){quick.insertAdjacentHTML('beforeend','<button class="quick-card" data-practice="whole"><span>↗</span><strong>整本遍历</strong><small>每天 50 词 · 每词 2 题</small></button>')}renderWholeProgress()});
function makeOptions(w,reverse=false){const key=reverse?'word':'meaning';const pool=state.words.filter(x=>x.id!==w.id);const clean=reverse?pool:pool.filter(x=>x.meaning&&!/待核验/.test(x.meaning));const source=(clean.length>=3?clean:pool).sort(()=>Math.random()-.5).slice(0,3);return [w[key],...source.map(x=>x[key])].sort(()=>Math.random()-.5)}
function repairOcrSavedMeanings(){if(!Array.isArray(window.FULL_OCR_WORDS))return;const map=new Map(window.FULL_OCR_WORDS.map(w=>[w.word.toLowerCase(),w]));let changed=false;state.words.forEach(w=>{if(w.source!=='ocr')return;const fresh=map.get(w.word.toLowerCase());if(fresh&&fresh.meaning&&!/待核验/.test(fresh.meaning)&&w.meaning!==fresh.meaning){w.meaning=fresh.meaning;w.notes=fresh.notes;changed=true}});if(changed)save()}
document.addEventListener('DOMContentLoaded',()=>{repairOcrSavedMeanings();renderHome()});
function meaningIsClean(v){if(typeof v!=='string')return false;const s=v.replace(/\s+/g,'').trim();if(!s||/待核验/.test(s)||s.length>22)return false;if(/[。！？!?]/.test(s))return false;if(/(我们|他们|她们|这个|那个|能够|可以|因为|所以|通常|经常|他的|她的|我的|在校|在工|句中|例句)/.test(s))return false;const han=(s.match(/[\u4e00-\u9fff]/g)||[]).length;return han>=2&&han<=16}
function repairBadOcrMeanings(){let changed=false;state.words.forEach(w=>{if(w.source!=='ocr'||meaningIsClean(w.meaning))return;w.notes=`原 OCR 释义已标记为待核验：${w.meaning||''}`;w.meaning='释义待核验';changed=true});if(changed)save()}
function makeOptions(w,reverse=false){const key=reverse?'word':'meaning';const pool=state.words.filter(x=>x.id!==w.id);const clean=reverse?pool:pool.filter(x=>meaningIsClean(x.meaning));const source=(clean.length>=3?clean:pool).sort(()=>Math.random()-.5).slice(0,3);return [w[key],...source.map(x=>x[key])].sort(()=>Math.random()-.5)}
document.addEventListener('DOMContentLoaded',()=>{repairBadOcrMeanings();renderHome()});
function meaningIsClean(v){if(typeof v!=='string')return false;const s=v.replace(/\s+/g,'').trim();if(!s||/待核验/.test(s)||s.length>22)return false;if(/[。！？!?]/.test(s))return false;if(/^(她|他|它|我|你|我们|你们|他们|她们|这|那|某|自己|自己的|他的|她的|它的|一个|一种|可以|能够|因为|所以|在|从|对|向|将|被|使|与|和)/.test(s))return false;if(/(我们|他们|她们|这个|那个|能够|可以|因为|所以|通常|经常|他的|她的|我的|在校|在工|句中|例句)/.test(s))return false;const han=(s.match(/[\u4e00-\u9fff]/g)||[]).length;return han>=2&&han<=16}
const _renderAnswerAreaClean=renderAnswerArea;renderAnswerArea=function(w,item){const type=answerType(),reverse=type==='reverse';if(!reverse&&item.options&&item.options.some(o=>!meaningIsClean(o)))item.options=null;_renderAnswerAreaClean(w,item)};
document.addEventListener('DOMContentLoaded',()=>{repairBadOcrMeanings();if(session?.queue)session.queue.forEach(q=>{q.options=null});if(state.lastSession?.queue)state.lastSession.queue.forEach(q=>{q.options=null});save();renderHome()});
const _renderQuestionFinal=renderQuestion;renderQuestion=function(){_renderQuestionFinal();const w=currentWord();if(!w)return;const type=answerType();if(type==='spell'){const prompt=meaningIsClean(w.meaning)?w.meaning:'请点击“听发音”后拼写单词';$('#questionPrompt').textContent=prompt;$('#questionLabel').textContent='SPELL / 听音写词'}else if(type==='listen'){const prompt=meaningIsClean(w.meaning)?w.meaning:'请听音选择对应单词';$('#questionPrompt').textContent=prompt;$('#questionLabel').textContent='LISTEN / 听音辨词'}};
function meaningIsClean(v){if(typeof v!=='string')return false;const s=v.replace(/\s+/g,'').trim();if(!s||/待核验/.test(s)||s==='—'||s.length>16)return false;if(/[。！？!?，,]/.test(s))return false;if(/^(她|他|它|我|你|我们|你们|他们|她们|这|那|某|自己|自己的|他的|她的|它的|一个|一种|可以|能够|因为|所以|在|从|对|向|将|被|使|与|和)/.test(s))return false;if(/(我们|他们|她们|这个|那个|能够|可以|因为|所以|通常|经常|他的|她的|我的|在校|在工|句中|例句|行动计划)/.test(s))return false;const han=(s.match(/[\u4e00-\u9fff]/g)||[]).length;return han>=2&&han<=12}
function makeOptions(w,reverse=false){const key=reverse?'word':'meaning';const seenWords=new Set([w.word.toLowerCase()]);const currentMeaning=String(w.meaning||'').replace(/\s+/g,'').trim();const pool=state.words.filter(x=>{const word=x.word.toLowerCase();if(x.id===w.id||seenWords.has(word))return false;if(!reverse&&!meaningIsClean(x.meaning))return false;if(!reverse&&String(x.meaning||'').replace(/\s+/g,'').trim()===currentMeaning)return false;seenWords.add(word);return true});const source=pool.sort(()=>Math.random()-.5).slice(0,3);return [w[key],...source.map(x=>x[key])].sort(()=>Math.random()-.5)}
function repairAllSavedIpa(){if(!Array.isArray(window.FULL_OCR_WORDS))return;const map=new Map(window.FULL_OCR_WORDS.map(w=>[w.word.toLowerCase(),w.ipa]));let changed=false;state.words.forEach(w=>{if(w.source==='ocr'&&map.has(w.word.toLowerCase())&&w.ipa!==map.get(w.word.toLowerCase())){w.ipa=map.get(w.word.toLowerCase());changed=true}});if(changed)save()}
document.addEventListener('DOMContentLoaded',()=>{repairAllSavedIpa();if(state.lastSession?.queue)state.lastSession.queue.forEach(q=>{q.options=null});save();renderHome()});
const MANUAL_IPA={testimony:'/ˈtestɪməni/',prosecute:'/ˈprɒsɪkjuːt/',legislate:'/ˈledʒɪsleɪt/',equity:'/ˈekwəti/',condemn:'/kənˈdem/',complain:'/kəmˈpleɪn/',testify:'/ˈtestɪfaɪ/',prosecution:'/ˌprɒsɪˈkjuːʃən/'};
document.addEventListener('DOMContentLoaded',()=>{let changed=false;state.words.forEach(w=>{const ipa=MANUAL_IPA[w.word.toLowerCase()];if(ipa&&w.ipa!==ipa){w.ipa=ipa;changed=true}});if(changed)save()});
function meaningIsClean(v){if(typeof v!=='string')return false;const s=v.replace(/\s+/g,'').trim();if(!s||/待核验/.test(s)||s.length>22)return false;if(/[。！？!?]/.test(s))return false;if((s.match(/[，,]/g)||[]).length>0&&s.length>9)return false;if(/^(她|他|它|我|你|我们|你们|他们|她们|这|那|某|自己|自己的|他的|她的|它的|一个|一种|可以|能够|因为|所以|在|从|对|向|将|被|使|与|和)/.test(s))return false;if(/(我们|他们|她们|这个|那个|能够|可以|因为|所以|通常|经常|他的|她的|我的|在校|在工|句中|例句)/.test(s))return false;const han=(s.match(/[\u4e00-\u9fff]/g)||[]).length;return han>=2&&han<=16}
function makeOptions(w,reverse=false){const key=reverse?'word':'meaning';const seenWords=new Set([w.word.toLowerCase()]);const currentMeaning=String(w.meaning||'').replace(/\s+/g,'').trim();const pool=state.words.filter(x=>{const word=x.word.toLowerCase();if(x.id===w.id||seenWords.has(word))return false;if(!reverse&&!meaningIsClean(x.meaning))return false;if(!reverse&&String(x.meaning||'').replace(/\s+/g,'').trim()===currentMeaning)return false;seenWords.add(word);return true});const source=pool.sort(()=>Math.random()-.5).slice(0,3);return [w[key],...source.map(x=>x[key])].sort(()=>Math.random()-.5)}
